-- use this file to map the AP item ids to your items
-- first value is the code of the target item and the second is the item type (currently only "toggle", "progressive" and "consumable" but feel free to expand for your needs!)
-- here are the SM items as an example: https://github.com/Cyb3RGER/sm_ap_tracker/blob/main/scripts/autotracking/item_mapping.lua
ITEM_MAPPING = {
    [47012] = {"empty_bottle","toggle"},
    [47053] = {"birds_nest", "toggle"},
    [47085] = {"net_launcher", "toggle"},
    [47086] = {"net_canister", "toggle"},
    [47028] = {"grass_plot", "toggle"},
    [47075] = {"shears", "toggle"},
    [47074] = {"metal_detector", "toggle"},
    [47076] = {"shovel", "toggle"},
    [47083] = {"machete", "toggle"},
    [47077] = {"sweep_net", "toggle"},
    [47056] = {"smelter", "toggle"},
    [47037] = {"bolt", "toggle"},
    [47039] = {"hinge", "toggle"},
    [47038] = {"circuit_board", "toggle"},
    [47035] = {"battery", "toggle"},
    [47044] = {"receiver", "toggle"},
    [47045] = {"antenna", "toggle"},
    [47043] = {"engine", "toggle"},
    [47046] = {"steering_wheel", "toggle"},
    [47087] = {"vasagatan_frequency", "toggle"},
    [47088] = {"balboa_frequency", "toggle"},
    [47089] = {"tangaroa_frequency", "toggle"},
    [47090] = {"varuna_point_frequency", "toggle"},
    [47091] = {"temperance_frequency", "toggle"},
    [47092] = {"utopia_frequency", "toggle"},
    [47093] = {"caravan_town_frequency", "toggle"},
}
